# Generated by Django 4.0 on 2025-02-24 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('customers', '0002_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Принят'), ('confirmed', 'Подтвержден'), ('preparing', 'Готовится'), ('in_delivery', 'Доставляется'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='accepted', max_length=20, verbose_name='Статус')),
                ('cart_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость всех позиций')),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость доставки')),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сервисный сбор')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Общая стоимость')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem', verbose_name='Позиция')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='customers.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
                'ordering': ('-created_at', '-id'),
                'unique_together': {('order', 'menu_item')},
            },
        ),
    ]
