# Generated by Django 4.0 on 2025-02-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активная зона')),
                ('zone_file', models.FileField(upload_to='', verbose_name='Файл зоны доставки')),
                ('zone_json', models.JSONField(blank=True, null=True, verbose_name='JSON зоны доставки')),
            ],
            options={
                'verbose_name': 'Зона доставки',
                'verbose_name_plural': 'Зоны доставок',
            },
        ),
    ]
