# Generated by Django 4.0 on 2025-03-01 20:18

from django.db import migrations, models
import localized_fields.fields.text_field


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_chat_id_alter_customer_telegram_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', localized_fields.fields.text_field.LocalizedTextField(required=['ru', 'uz'], verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
    ]
