# Generated by Django 4.0 on 2025-03-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='test', verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
