# Generated by Django 4.0 on 2025-03-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.TextField(null=True),
        ),
    ]
