# Generated by Django 4.0 on 2025-03-04 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_state_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service_fee',
        ),
    ]
