# Generated by Django 4.0 on 2025-03-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_remove_order_cart_amount_remove_order_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cashback',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cashback'),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Имя'),
        ),
    ]
