# Generated by Django 4.0 on 2025-03-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_customer_cashback_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='for_pickup',
            field=models.BooleanField(default=False, verbose_name='Самовывоз'),
        ),
        migrations.AddField(
            model_name='order',
            name='for_pickup',
            field=models.BooleanField(default=False, verbose_name='Самовывоз'),
        ),
    ]
