# Generated by Django 4.0 on 2025-03-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_customer_for_pickup_order_for_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='used_cashback',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Использованный cashback'),
        ),
    ]
