# Generated by Django 4.0 on 2025-03-15 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_order_is_finished_order_used_cashback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='used_cashback',
        ),
    ]
