# Generated by Django 4.0 on 2025-03-20 23:13

from django.db import migrations, models
import localized_fields.fields.text_field


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_remove_order_used_cashback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='language',
            field=models.CharField(blank=True, choices=[('ru', 'Русский'), ('uz', 'Узбекский'), ('qp', 'Каракалпакский')], max_length=5, null=True, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=localized_fields.fields.text_field.LocalizedTextField(required=['ru'], verbose_name='Текст'),
        ),
    ]
