# Generated by Django 4.0 on 2025-04-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_alter_customer_language_alter_notification_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('waiting', 'Ожидает подтверждения'), ('confirmed', 'Подтвержден'), ('rejected', 'Отклонен')], max_length=20, null=True, verbose_name='Статус платежа'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Наличными'), ('card', 'Картой')], default='cash', max_length=10, verbose_name='Тип платежа'),
        ),
    ]
