"""
Django settings for MenuBot project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from collections import OrderedDict

# Build paths inside the project like this: BASE_DIR / 'subdir'.
PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4+$78uo)&2vi!!2nyrh1@x=#)=2@ed_hr!888_)_^mf_l#ztp='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

THIRD_PARTY_APPS = [
    "rest_framework",
    "corsheaders",
    "phonenumber_field",
    "constance",
    "constance.backends.database",
    # "django_celery_beat",
    "django.contrib.postgres",
    "localized_fields",
    'django_cleanup.apps.CleanupConfig',
    'adminsortable2',
]

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

LOCAL_APPS = [
    'customers.apps.CustomersConfig',
    'menu.apps.MenuConfig',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'common.middleware.LanguageHeaderMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MenuBot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(PROJECT_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MenuBot.wsgi.application'


REST_FRAMEWORK = {
    'COERCE_DECIMAL_TO_STRING': False,
}

APPEND_SLASH = False


REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = os.getenv("REDIS_PORT")
REDIS_DB_FOR_CACHE = os.getenv("REDIS_DB_FOR_CACHE")
REDIS_AS_CACHE_URL = "redis://{host}:{port}/{db_index}".format(
    host=REDIS_HOST,
    port=REDIS_PORT,
    db_index=REDIS_DB_FOR_CACHE,
)
REDIS_DB_FOR_CELERY = os.getenv("REDIS_DB_FOR_CELERY", "0")
REDIS_AS_BROKER_URL = "redis://{host}:{port}/{db_index}".format(
    host=REDIS_HOST,
    port=REDIS_PORT,
    db_index=REDIS_DB_FOR_CELERY,
)

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_AS_CACHE_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'psqlextra.backend',
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru'
LANGUAGES = (
    ("ru", "Русский"),
    ("uz", "Узбекский"),
)

TIME_ZONE = 'Asia/Qyzylorda'
USE_I18N = True
USE_L10N = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(PROJECT_DIR, 'static')
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(PROJECT_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CELERY_BROKER_URL = REDIS_AS_BROKER_URL
# CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers.DatabaseScheduler"

CELERY_RESULT_EXTENDED = False
CELERY_RESULT_EXPIRES = 3600
CELERY_ALWAYS_EAGER = False
CELERY_ACKS_LATE = True
CELERY_TASK_PUBLISH_RETRY = False
CELERY_DISABLE_RATE_LIMITS = False
CELERY_TASK_TRACK_STARTED = True


CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'
CONSTANCE_CONFIG = {
    "CASHBACK_PERCENTAGE": (2, '% кешбэка'),
    "POPULAR_CATEGORY_RU": ("Популярное", 'Популярная категория (RU)'),
    "POPULAR_CATEGORY_UZ": ("Mashhur", 'Популярная категория (UZ)'),
    "START_TIME": ("08:00", 'Время открытия'),
    "END_TIME": ("22:30", 'Время закрытия'),
    "ADDRESS_MESSAGE_RU": ("Отправьте свое местоположение", 'Просьба отправить адрес (RU)'),
    "ADDRESS_MESSAGE_UZ": ("Joylashuvingizni yuboring", 'Просьба отправить адрес (UZ)'),
    "EDIT_LANGUAGE_BUTTON_RU": ("Изменить язык интерфейса", 'Кнопка "Изменить язык интерфейса" (RU)'),
    "EDIT_LANGUAGE_BUTTON_UZ": ("Interfeys tilini o'zgartiring", 'Кнопка "Изменить язык интерфейса" (UZ)'),
    "EDIT_PHONE_BUTTON_RU": ("Изменить номер телефона", 'Кнопка "Изменить номер телефона"" (RU)'),
    "EDIT_PHONE_BUTTON_UZ": ("Telefon raqamini o'zgartiring", 'Кнопка "Изменить номер телефона"" (UZ)'),
    "GET_TO_MAIN_BUTTON_RU": ("На главную", 'Кнопка "На главную" (RU)'),
    "GET_TO_MAIN_BUTTON_UZ": ("На главную", 'Кнопка "На главную" (UZ)'),
    "GET_BACK_BUTTON_RU": ("🔙Назад", 'Кнопка "Назад" (RU)'),
    "GET_BACK_BUTTON_UZ": ("🔙Orqaga", 'Кнопка "Назад" (UZ)'),
    "LANGUAGE_BUTTON_RU": ("🇷🇺Русский", 'Кнопка "Русский язык" (RU)'),
    "LANGUAGE_BUTTON_UZ": ("🇺🇿O'zbek", 'Кнопка "Узбекский язык" (UZ)'),
    "LANGUAGES_MESSAGE": ('Выберите язык / Tilni tanlang', 'Просьба выбрать язык'),
    "LANGUAGES_MESSAGE_RU": ('Выберите язык', 'Просьба выбрать язык (RU)'),
    "LANGUAGES_MESSAGE_UZ": ('Tilni tanlang', 'Просьба выбрать язык (UZ)'),
    "PRESENT_ON": (False, 'Подарок ВКЛ/ВЫКЛ'),
    "PRESENT_IMAGE_URL": ('https://kazpravda.kz/media/uploads/publication2/694/39/69439-image.jpg', 'Ссылка на картинку подарка'),
    "PRESENT_RU": ('Текст о подарке', 'Текст о подарке (RU)'),
    "PRESENT_UZ": ('Текст о подарке', 'Текст о подарке (UZ)'),
    "PRESENT_CART_RU": ('Текст о подарке в корзине', 'Текст о подарке в корзине (RU)'),
    "PRESENT_CART_UZ": ('Текст о подарке в корзине', 'Текст о подарке в корзине (UZ)'),
    "MAIN_MESSAGE_RU": ('Для оформления заказа нажмите кнопку "🍴Меню"', 'Сообщение в меню (RU)'),
    "MAIN_MESSAGE_UZ": ('Buyurtma berish uchun "🍴Menyu" tugmasini bosing', 'Сообщение в меню (UZ)'),
    "MAIN_MESSAGE_1_RU": ('Для оформления заказа нажмите кнопку "🍴Меню"', 'Сообщение в меню без приветствия (RU)'),
    "MAIN_MESSAGE_1_UZ": ('Buyurtma berish uchun "🍴Menyu" tugmasini bosing', 'Сообщение в меню без приветствия (UZ)'),
    "MENU_BUTTON_RU": ('🍴Меню', 'Кнопка "Меню" (RU)'),
    "MENU_BUTTON_UZ": ('🍴Menyu', 'Кнопка "Меню" (UZ)'),
    "MENU_MESSAGE_RU": ('Закажите с интерактивного меню', 'Просьба перейти в меню (RU)'),
    "MENU_MESSAGE_UZ": ('Interaktiv menyudan buyurtma bering', 'Просьба перейти в меню (UZ)'),
    "PHONE_MESSAGE_RU": ('Нажмите на кнопку "📞Отправить контакт"', 'Просьба отправить контакт" (RU)'),
    "PHONE_MESSAGE_UZ": ('"📞Kontaktni yuboring" tugmasini bosing', 'Просьба отправить контакт" (UZ)'),
    "SET_ADDRESS_BUTTON_RU": ('📍Поделиться местоположением', 'Кнопка "Поделиться местоположением" (RU)'),
    "SET_ADDRESS_BUTTON_UZ": ('📍Joylashuvni ulashish', 'Кнопка "Поделиться местоположением" (UZ)'),
    "SET_PHONE_RU": ("📞Отправить контакт", 'Кнопка "Отправить контакт" (RU)'),
    "SET_PHONE_UZ": ("📞Kontaktni yuboring", 'Кнопка "Отправить контакт" (UZ)'),
    "SETTINGS_BUTTON_RU": ('⚙️Настройки', 'Кнопка "Настройки" (RU)'),
    "SETTINGS_BUTTON_UZ": ('⚙️Sozlamalar', 'Кнопка "Настройки" (UZ)'),
    "SETTINGS_MESSAGE_RU": ('Выберите настройку', 'Сообщение в разделе "Настройки" (RU)'),
    "SETTINGS_MESSAGE_UZ": ('Sozlamani tanlang', 'Сообщение в разделе "Настройки" (UZ)'),
    "WEB_APP_URL": ('https://miraapa.uz', 'Ссылка на web app'),
    "WEB_APP_BUTTON_RU": ('Интерактивное меню', 'Кнопка "Интерактивное меню" (RU)'),
    "WEB_APP_BUTTON_UZ": ('Interaktiv menyu', 'Кнопка "Интерактивное меню" (UZ)'),
    "NOT_IN_DELIVERY_ZONE_RU": ('Ваш адрес вне зоны доставки', 'Сообщение вне зоны доставки (RU)'),
    "NOT_IN_DELIVERY_ZONE_UZ": ('Sizning manzilingiz yetkazib berish hududidan tashqarida', 'Сообщение вне зоны доставки (UZ)'),
    "DELIVERY_RU": ('Стоимость доставки оплачивается отдельно водителю службы такси.', 'Используйте кнопку меню (RU)'),
    "DELIVERY_UZ": ("Yetkazib berish narxi taksi haydovchisiga alohida to'lanadi.", 'Используйте кнопку меню (UZ)'),
    "PICKUP_RU": ('Наш адрес: г. Нукус, ул. Досназарова, 1', 'Используйте кнопку меню (RU)'),
    "PICKUP_UZ": ("Bizning manzil: Nukus sh., Dosnazarov k., 1", 'Используйте кнопку меню (UZ)'),
    "BILL_INITIAL_RU": ('Новый заказ', 'Счет начальный текст (RU)'),
    "BILL_INITIAL_UZ": ('Yangi buyurtma', 'Счет начальный текст (UZ)'),
    "BILL_TOTAL_RU": ('Итого', 'Счет итого (RU)'),
    "BILL_TOTAL_UZ": ('Jami', 'Счет итого (UZ)'),
    "BILL_FINAL_RU": ('Благодарим за заказ!\nОператор свяжется с вами в ближайшее время.', 'Счет финальный текст (RU)'),
    "BILL_FINAL_UZ": ("Buyurtmangiz uchun rahmat!\nTez orada operator siz bilan bog'lanadi.", 'Счет финальный текст (UZ)'),
    "NOT_WORKING_TIME_RU": ("К сожалению, в данное время мы не принимаем заказы.", 'Текст о нерабочем времени (RU)'),
    "NOT_WORKING_TIME_UZ": ("Afsuski, biz hozircha buyurtmalarni qabul qilmayapmiz.", 'Текст о нерабочем времени (UZ)'),
    "DELIVERY_TYPE_RU": ("Доставка или самовывоз?", 'Доставка или самовывоз? (RU)'),
    "DELIVERY_TYPE_UZ": ("Yetkazib berishmi yoki olib ketishmi?", 'Доставка или самовывоз? (UZ)'),
    "DELIVERY_BUTTON_RU": ("Доставка", 'Кнопка "Доставка" (RU)'),
    "DELIVERY_BUTTON_UZ": ("Yetkazib berish", 'Кнопка "Доставка" (UZ)'),
    "PICKUP_BUTTON_RU": ("Самовывоз", 'Кнопка "Самовывоз" (RU)'),
    "PICKUP_BUTTON_UZ": ("Olib ketish", 'Кнопка "Самовывоз" (UZ)'),
}
CONSTANCE_CONFIG_FIELDSETS = OrderedDict([
    ("Кешбэк", (
        "CASHBACK_PERCENTAGE",
    )),
    ("Подарок", (
        "PRESENT_ON",
        "PRESENT_IMAGE_URL",
        "PRESENT_RU",
        "PRESENT_UZ",
        "PRESENT_CART_RU",
        "PRESENT_CART_UZ",
    )),
    ("Настройки WebView",(
        "POPULAR_CATEGORY_RU",
        "POPULAR_CATEGORY_UZ",
        "START_TIME",
        "END_TIME",
    )),
    ("Счет. Текст",(
        "BILL_INITIAL_RU",
        "BILL_INITIAL_UZ",
        "BILL_TOTAL_RU",
        "BILL_TOTAL_UZ",
        "BILL_FINAL_RU",
        "BILL_FINAL_UZ",
    )),
    ("Настройки бота",(
        "ADDRESS_MESSAGE_RU",
        "ADDRESS_MESSAGE_UZ",
        "EDIT_LANGUAGE_BUTTON_RU",
        "EDIT_LANGUAGE_BUTTON_UZ",
        "EDIT_PHONE_BUTTON_RU",
        "EDIT_PHONE_BUTTON_UZ",
        "GET_TO_MAIN_BUTTON_RU",
        "GET_TO_MAIN_BUTTON_UZ",
        "GET_BACK_BUTTON_RU",
        "GET_BACK_BUTTON_UZ",
        "LANGUAGE_BUTTON_RU",
        "LANGUAGE_BUTTON_UZ",
        "LANGUAGES_MESSAGE",
        "LANGUAGES_MESSAGE_RU",
        "LANGUAGES_MESSAGE_UZ",
        "MAIN_MESSAGE_RU",
        "MAIN_MESSAGE_UZ",
        "MAIN_MESSAGE_1_RU",
        "MAIN_MESSAGE_1_UZ",
        "MENU_BUTTON_RU",
        "MENU_BUTTON_UZ",
        "MENU_MESSAGE_RU",
        "MENU_MESSAGE_UZ",
        "PHONE_MESSAGE_RU",
        "PHONE_MESSAGE_UZ",
        "SET_ADDRESS_BUTTON_RU",
        "SET_ADDRESS_BUTTON_UZ",
        "SET_PHONE_RU",
        "SET_PHONE_UZ",
        "SETTINGS_BUTTON_RU",
        "SETTINGS_BUTTON_UZ",
        "SETTINGS_MESSAGE_RU",
        "SETTINGS_MESSAGE_UZ",
        "WEB_APP_URL",
        "WEB_APP_BUTTON_RU",
        "WEB_APP_BUTTON_UZ",
        "NOT_IN_DELIVERY_ZONE_RU",
        "NOT_IN_DELIVERY_ZONE_UZ",
        "DELIVERY_RU",
        "DELIVERY_UZ",
        "PICKUP_RU",
        "PICKUP_UZ",
        "NOT_WORKING_TIME_RU",
        "NOT_WORKING_TIME_UZ",
        "DELIVERY_TYPE_RU",
        "DELIVERY_TYPE_UZ",
        "DELIVERY_BUTTON_RU",
        "DELIVERY_BUTTON_UZ",
        "PICKUP_BUTTON_RU",
        "PICKUP_BUTTON_UZ",
    ))
])
CONSTANCE_IGNORE_ADMIN_VERSION_CHECK = True


CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'access-control-allow-origin',
    'accept',
    'accept-encoding',
    'accept-language',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'cookie',
    'language',
]

CSRF_TRUSTED_ORIGINS = ['https://miraapa.uz', 'https://www.miraapa.uz']
