# Generated by Django 4.0 on 2025-03-20 23:13

from django.db import migrations
import localized_fields.fields.char_field
import localized_fields.fields.text_field


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_is_cart_category_alter_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=localized_fields.fields.char_field.LocalizedCharField(required=['ru'], verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=localized_fields.fields.text_field.LocalizedTextField(required=['ru'], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=localized_fields.fields.char_field.LocalizedCharField(required=['ru'], verbose_name='Наименование'),
        ),
    ]
